import type { Language } from "../../i18n/types";

/** Common words, most frequent first (approximate order). Lowercase, no duplicates. */
export const PREDICT_WORDS: Record<Language, readonly string[]> = {
  fr: [
    "le", "de", "un", "être", "et", "à", "il", "avoir", "ne", "je",
    "son", "que", "se", "pas", "plus", "pouvoir", "par", "ce", "avec", "tout",
    "nous", "ou", "mais", "en", "aussi", "bien", "comme", "qui", "lui", "elle",
    "donc", "très", "après", "aller", "vouloir", "me", "mon", "dans", "peu", "on",
    "vous", "moi", "jour", "an", "semaine", "heure", "minute", "temps", "vie", "mort",
    "monde", "homme", "femme", "enfant", "parent", "ami", "frère", "sœur", "mère", "père",
    "maison", "appartement", "bureau", "école", "université", "église", "hôpital", "restaurant", "café", "magasin",
    "voiture", "train", "avion", "bateau", "vélo", "moto", "autobus", "route", "chemin", "livre",
    "journal", "magazine", "article", "lettre", "mail", "téléphone", "ordinateur", "internet", "site", "couleur",
    "bleu", "rouge", "vert", "jaune", "noir", "blanc", "gris", "rose", "orange", "grand",
    "petit", "bon", "mauvais", "nouveau", "vieux", "jeune", "fort", "faible", "rapide", "lent",
    "haut", "bas", "long", "court", "large", "étroit", "épais", "fin", "lourd", "léger",
    "froid", "chaud", "sec", "mouillé", "propre", "sale", "beau", "laid", "joli", "facile",
    "difficile", "simple", "complexe", "clair", "obscur", "calme", "bruyant", "travail", "emploi", "profession",
    "métier", "carrière", "industrie", "commerce", "finance", "banque", "entreprise", "ingénieur", "logiciel", "projet",
    "programmation", "dictionnaire", "prédiction", "satellite", "tennis", "réseau", "argent", "prix", "salaire", "revenu",
    "dépense", "économie", "richesse", "pauvreté", "luxe", "confort", "nourriture", "pain", "viande", "poisson",
    "fruits", "légumes", "eau", "boisson", "alcool", "thé", "sport", "jeu", "musique",
    "art", "danse", "théâtre", "cinéma", "film", "chanson", "comédie", "drame", "tragédie", "aventure",
    "mystère", "action", "nature", "montagne", "vallée", "rivière", "lac", "mer", "océan", "île",
    "plage",
  ],
  en: [
    "the", "be", "to", "of", "and", "a", "in", "that", "have", "i",
    "it", "for", "not", "on", "with", "he", "as", "you", "do", "at",
    "this", "but", "his", "by", "from", "they", "we", "say", "her", "she",
    "or", "an", "will", "my", "one", "all", "would", "there", "their", "what",
    "so", "up", "out", "if", "about", "who", "get", "which", "go", "me",
    "when", "make", "can", "like", "time", "no", "just", "him", "know", "take",
    "people", "into", "year", "your", "good", "some", "could", "them", "see", "other",
    "than", "then", "now", "look", "only", "come", "its", "over", "think", "also",
    "back", "after", "use", "two", "how", "our", "work", "first", "well", "way",
    "even", "new", "want", "because", "any", "these", "give", "day", "most", "us",
    "is", "was", "are", "been", "being", "does", "did", "has", "had", "going",
    "went", "made", "making", "said", "saying", "got", "came", "coming", "should",
    "may", "might", "must", "ought", "need", "dare", "man", "woman",
    "child", "person", "family", "friend", "brother", "sister", "mother", "father", "parent", "son",
    "daughter", "uncle", "aunt", "cousin", "house", "home", "room", "door", "window", "wall",
    "roof", "floor", "building", "street", "city", "town", "country", "world", "earth", "sky",
    "sun", "moon", "star", "light", "dark", "black", "white", "red", "blue", "green",
    "yellow", "orange", "purple", "car", "bus", "train", "plane", "boat", "ship", "bike",
    "truck", "road", "path", "book", "paper", "pen", "pencil", "desk", "table", "chair",
    "bed", "phone", "computer", "school", "college", "university", "office", "hospital", "church", "restaurant",
    "shop", "store", "market",
  ],
};
