import React from "react";
import "./app.css";
import { LanguageProvider } from "../i18n/LanguageContext";

export const metadata = {
  title: "Portfolio - Corentin Bunaux",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fr">
      <body>
        <LanguageProvider>{children}</LanguageProvider>
      </body>
    </html>
  );
}
