/* eslint-disable @next/next/no-img-element --
 * `no-img-element` steers towards `next/image`, which cannot do the job here.
 * `next.config.mjs` sets `output: "export"`, which requires
 * `images: { unoptimized: true }`, and under that flag `next/image` emits no
 * `srcset` and performs no format conversion — it renders a plain `<img>` and
 * saves zero bytes. `<picture>` is the only HTML mechanism that negotiates
 * AVIF with a WebP fallback, and it needs a real `<img>` child. This file is
 * the single place in the codebase where a raw `<img>` is written; every call
 * site goes through the component below.
 */

import type { CSSProperties } from "react";
import manifest from "../data/imageManifest.json";

type ImageMeta = { width: number; height: number } | { svg: true; width: number; height: number };

/** Generated by `npm run optimize:images`; keys are extensionless, e.g. `/img/cv`. */
const images = manifest as Record<string, ImageMeta | undefined>;

export type OptimizedImageProps = {
  /** Extensionless public path, e.g. `/img/cv` or `/logos/safran`. */
  src: string;
  alt: string;
  className?: string;
  style?: CSSProperties;
  sizes?: string;
  /** Above-the-fold images load eagerly at high priority instead of lazily. */
  priority?: boolean;
};

export function OptimizedImage({
  src,
  alt,
  className,
  style,
  sizes,
  priority = false,
}: OptimizedImageProps) {
  const meta = images[src];

  if (!meta) {
    // Fail loudly at build time rather than shipping a 404 image: this only
    // happens when a master is renamed without re-running the optimizer.
    throw new Error(
      `OptimizedImage: "${src}" is not in the image manifest. Run \`npm run optimize:images\`.`
    );
  }

  const loading = priority ? "eager" : "lazy";
  const fetchPriority = priority ? "high" : undefined;

  if ("svg" in meta) {
    return (
      <img
        src={`${src}.svg`}
        alt={alt}
        width={meta.width}
        height={meta.height}
        className={className}
        style={style}
        loading={loading}
        fetchPriority={fetchPriority}
        decoding="async"
      />
    );
  }

  return (
    // `display: contents` keeps <picture> out of the layout entirely, so the
    // <img> lays out exactly as it did before it was wrapped (absolute
    // positioning and percentage sizing still resolve against the real parent).
    <picture style={{ display: "contents" }}>
      <source srcSet={`${src}.avif`} type="image/avif" sizes={sizes} />
      <img
        src={`${src}.webp`}
        alt={alt}
        width={meta.width}
        height={meta.height}
        sizes={sizes}
        className={className}
        style={style}
        loading={loading}
        fetchPriority={fetchPriority}
        decoding="async"
      />
    </picture>
  );
}
